kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "example-nodejs.goodbyeworld.name" . }}
  labels:
    kubed: {{ template "example-nodejs.name" . }}
    component: goodbyeworld
    generator: nodejs
spec:
  selector:
    matchLabels:
      kubed: {{ template "example-nodejs.name" . }}
      component: goodbyeworld
  replicas: {{ default .Values.goodbyeworld.replicaCount 1 }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        kubed: {{ template "example-nodejs.name" . }}
        component: goodbyeworld
    spec:
      containers:
        - name: goodbyeworld
          image: "{{ .Values.goodbyeworld.image.repository }}:{{ .Values.goodbyeworld.image.tag }}"
          imagePullPolicy: {{ default .Values.goodbyeworld.image.pullPolicy "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
