kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "example-nodejs.static.name" . }}
  labels:
    kubed: {{ template "example-nodejs.name" . }}
    component: static
spec:
  selector:
    matchLabels:
      kubed: {{ template "example-nodejs.name" . }}
      component: static
  replicas: {{ default .Values.static.replicaCount 1 }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        kubed: {{ template "example-nodejs.name" . }}
        component: static
    spec:
      containers:
        - name: static
          image: "{{ .Values.static.image.repository }}:{{ .Values.static.image.tag }}"
          imagePullPolicy: {{ default .Values.static.image.pullPolicy "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
